const drawButton=document.getElementById('drawButton'),capsule=document.getElementById('capsule'),result=document.getElementById('result'),totalDraws=document.getElementById('totalDraws'),collection=document.getElementById('collection'),statusText=document.getElementById('statusText'),drawResult=document.getElementById('drawResult'),records=document.getElementById('records');let isDrawing=false,holdTimer=null,holdInterval=null;
function renderRateCounts(counts={}){const rates=['85','13.9999','1','0.0001'];collection.innerHTML=rates.map(rate=>`<div class="collection-card"><div class="collection-name">${rate}%</div><div class="collection-rate">${(counts[rate]||0).toLocaleString()}回</div></div>`).join('')}
async function loadStatus(){try{const res=await fetch('/api/status');if(!res.ok)throw new Error();const data=await res.json();totalDraws.textContent=(data.totalDraws||0).toLocaleString();renderRateCounts(data.rateCounts||{});if(data.completed) lockGame()}catch{statusText.textContent='読み込みに失敗しました'}}
function lockGame(){drawButton.disabled=true;drawButton.textContent='🎉 クリア済み';drawButton.removeEventListener('pointerdown',startHold);document.body.classList.add('game-completed')}
async function loadRecords(){try{const res=await fetch('/api/records');if(!res.ok)throw new Error();const data=await res.json();if(!data.records.length){records.innerHTML='<div class="empty-records">まだ達成者はいません。最初の1人を目指そう！</div>';return}records.innerHTML=data.records.slice().reverse().map(r=>`<div class="record-row"><span class="record-rank">#${r.rank}</span><strong>${r.draws.toLocaleString()}回目</strong><span class="record-date">${new Date(r.at).toLocaleString('ja-JP')}</span></div>`).join('')}catch{records.innerHTML='<div class="empty-records">記録を読み込めませんでした</div>'}}
function shareOnX(drawNumber){const text=`🎉 0.0001%を引いた！\n${drawNumber.toLocaleString()}回目で達成しました！\n\n#0.0001パーセントガチャ #ガチャ`;const url=`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(location.href)}`;window.open(url,'_blank','noopener,noreferrer')}
function startHold(){clearTimeout(holdTimer);clearInterval(holdInterval);holdTimer=setTimeout(()=>{holdInterval=setInterval(()=>{if(!isDrawing)drawOnce()},330)},450)}
function showResult(item,drawNumber){drawResult.textContent=`${drawNumber.toLocaleString()}回目　${item.rate}%`;if(item.target===true){lockGame();document.body.classList.add('target-hit');result.className='result card result-target';result.innerHTML=`<div class="result-name">🎉 0.0001%を引いた！ 🎉</div><div class="result-rate">COMPLETE!!</div><div class="result-count">${drawNumber.toLocaleString()}回目</div><button class="share-button" id="shareButton">𝕏 Xに投稿する</button>`;document.getElementById('shareButton').addEventListener('click',()=>shareOnX(drawNumber));loadRecords();setTimeout(()=>document.body.classList.remove('target-hit'),1200)}else{result.className='result card hidden';result.innerHTML=''}}
async function drawOnce(){if(isDrawing)return;isDrawing=true;drawButton.classList.add('is-drawing');statusText.textContent='';capsule.classList.remove('shake','pop');void capsule.offsetWidth;capsule.classList.add('shake');try{const res=await fetch('/api/draw',{method:'POST'});if(!res.ok)throw new Error();const data=await res.json();capsule.classList.remove('shake');capsule.classList.add('pop');showResult(data.item,data.totalDraws);totalDraws.textContent=data.totalDraws.toLocaleString();renderRateCounts(data.rateCounts||{})}catch{statusText.textContent='ガチャに失敗しました'}finally{isDrawing=false;drawButton.classList.remove('is-drawing')}}
drawButton.addEventListener('click',drawOnce);drawButton.addEventListener('pointerdown',startHold);function stopHold(){clearTimeout(holdTimer);clearInterval(holdInterval);holdTimer=null;holdInterval=null}['pointerup','pointercancel','pointerleave'].forEach(e=>drawButton.addEventListener(e,stopHold));loadStatus();loadRecords();
